enum MutationTypes {
  CHANGE_NUMBER = 'CHANGE_NUMBER',
  CHANGE_ADVICE = 'CHANGE_ADVICE',
  CHANGE_SIDEBAR_COLLAPSE = 'CHANGE_SIDEBAR_COLLAPSE',
  TOGGLE_MODAL = 'TOGGLE_MODAL',
  TOGGLE_CREATE_MODAL = 'TOGGLE_CREATE_MODAL',
  CHANGE_USER_LOGGED_IN = 'CHANGE_USER_LOGGED_IN',
}

export default MutationTypes;
