enum MutationTypes {
  CHANGE_NUMBER = 'CHANGE_NUMBER',
  CHANGE_ADVICE = 'CHANGE_ADVICE',
  CHANGE_SIDEBAR_COLLAPSE = 'CHANGE_SIDEBAR_COLLAPSE',
  TOGGLE_MODAL = 'TOGGLE_MODAL',
}

export default MutationTypes;
